### ISSUE TITLE
Story for first area, Merrymellow Marsh

### ISSUE THREAD

**Issue by Poobslag** [Poobslag/turbofat#719]
This will have a few smaller linked stories, as this is an epic. But it encompasses characters, cutscenes and environments for the first area. It does not necessarily encompass the details of the levels, it's OK if the levels themselves are placeholders for now.

- [x] #720 The intro/outro cutscenes are all there
- [X] #721 All of the level data exists, even if they're just cutscenes with an uninteresting placeholder level 
- [x] #718 All of the characters are on the overworld, and you can walk up and talk to them
- [x] #173 #85 #84 #78 #77 The environment looks distinctive and marshey

Here's the full projected story for the area to refer back to.

```
part 1: you meet the team; skins, shirts and bones are the cooks and they're all just OK. you work with each of them to help build their skills
 -a) hello everyone

 -b1) hello bones
 -b2) hello shirts
 -b3) hello skins

part 2: skins and bones fall in love with you. you continue working with the team to help build their skills
 -c) pulling for everyone

 -d1) pulling for bones
 -d2) pulling for shirts
 -d3) pulling for skins

part 3: the business is popular. but before you can move on -- you have to divorce skins and bones
 -e) let's all get merry

 -f1) goodbye bones
 -f2) goodbye shirts
 -f3) goodbye skins

 -g) goodbye everyone

(culminates with a little cutscene where you and master fat reflect on what you've learned, to My Fatness Pal)

(other levels)
 -h1) we won't forget bones
 -h2) we won't forget shirts
 -h3) we won't forget skins

 -?1) ???
 -?2) ???
 -?3) ???
 -?4) ???
```

**Comment by Poobslag** [comment]
-launching first cutscene changes scene to restaurant interior

goal: first indoor multi-character cutscene
-changes scene to restaurant interior
-all characters present
-restaurant is visible outdoors
----------
-some characters spawn indoors
-some characters spawn outdoors
-first indoor story character always spawns indoors if their cutscene demands it

**Comment by Poobslag** [comment]
The central story is done. There are a few side stories which would be nice to tell, but it's enough that I'd say this story is done.
