### ISSUE TITLE
Create intro/outro cutscenes for first area, Merrymellow marsh

### ISSUE THREAD

**Issue by Poobslag** [Poobslag/turbofat#720]
See #719 for full detail of how the cutscenes should be organized.

- [x] Storyboard intro/outro cutscenes
- [x] Create a single cutscene
  - [x] Design characters
  - [x] Intro dialog
  - [x] Outro dialog
  - [x] Appropriate scenario
  - [x] Appropriate emotes and movement
- [x] Add support for another language, such as spanish #372
- [x] Create cutscene dialog tools #782
- [x] Create cutscene scripting tools #783

Cutscenes:
- [ ] Act 1
  - [x] (puzzle) Meeting the staff
  - [x] (Meeting the competition)
  - [ ] (Scaring away Rhonk)
  - [ ] (puzzle) Finding new customers
  - [x] (puzzle) Hello Shirts
  - [x] (puzzle) Hello Bones
  - [x] (puzzle) Hello Skins
- [ ] Act 2
  - [x] (*) (puzzle) It's kind of time to leave
  - [x] (puzzle) Pulling for skins
  - [x] (puzzle) Pulling for bones
  - [x] (puzzle) Learning about Skins and Bones from Shirts
  - [ ] (Learning about Rhonk from Shirts)
  - [x] (The Buttercup Cafe falls on hard times)
- [ ] Act 3
  - [x] (*) It's REALLY time to leave
  - [x] (puzzle) Goodbye bones
  - [x] (puzzle) Goodbye skins
  - [x] (puzzle) Goodbye shirts
  - [ ] (Rhonk forgives us)
  - [x] (*) Goodbye everyone

**Comment by Poobslag** [comment]
* Storyboard intro/outro cutscenes
  * Create a single cutscene
    * Intro dialog
    * Outro dialog (?)
    * Appropriate scenery
    * Appropriate emotes and movement

After we do these two tasks, this should lay the groundwork for the remaining cutscenes.

**Comment by Poobslag** [comment]
The story dependencies (this dialog happens before this one, etc) were implemented with a BNF parser adapted from this javascript implementation

https://github.com/cosinekitty/parser/blob/master/expression.js

There are also a few cutscene streamlining/improvements I'd like to implement

- [ ] 'just wherever' cutscenes need a way to specify a location... something like, 'here's where the cutscene happens, but don't bother changing scenes'

**Comment by Poobslag** [comment]
Most cutscenes are done, except for three centered around Rhonk and a few centered around gaining other customers.
